feat: add lazy select
libp2p/js-libp2p-multistream-select pull request #18
Opened 2022-08-08 17:11 UTC by alanshaw

Implements lazy select as seen in go-multistream (https://github.com/multiformats/go-multistream/blob/master/lazyClient.go) and rust libp2p (https://github.com/libp2p/rust-libp2p/pull/1855)

Can be used to avoid a round trip when the dialer has only a single protocol to select from.

2022-08-12 09:42 UTC, alanshaw commented
> I wonder if there's any value in the handshake when there's only one protocol we want to speak? We could just send the protocol and immediately start sending data, then the remote would close the stream if it doesn't support the protocol.

That's urh, exactly what this does...unless I'm misunderstanding what you mean.

Lazy select does this:

```mermaid
sequenceDiagram
    participant initiator
    participant receiver
    initiator->>receiver: /multistream/1.0.0 /bitswap/1.2.0 DATA
    receiver->>initiator: /multistream/1.0.0 /bitswap/1.2.0
```

VS regular select:

```mermaid
sequenceDiagram
    participant initiator
    participant receiver
    initiator->>receiver: /multistream/1.0.0 /bitswap/1.2.0
    receiver->>initiator: /multistream/1.0.0 /bitswap/1.2.0
     initiator->>receiver: DATA
```

In lazy select the receiver will respond with `na` if not supported and _then_ the stream will be closed by the initiator. The receiver may receive _some_ data but 🤷‍♂️.

In my fork I expose this to users via a `lazy` option so you can do `libp2p.dialProtocol('/bitswap', ma, { lazy: true })` but things have changed around a bit so I think the upgrader would do that logic now...

https://github.com/web3-storage/js-libp2p-multistream-select/blob/15ac7f3f632df9dadf71b975857cc18bc9dc57a6/src/index.ts#L43-L45

2022-08-12 13:08 UTC, achingbrain commented
Yeah, I just mean you have to explicitly select to be lazy - it looks like lazy is better since there are fewer round-trips involved, so why not default to that instead of doing the whole handshake dance.

2022-08-12 13:36 UTC, achingbrain commented
I'm just thinking out loud, not a requirement for merging this PR!

2022-08-12 13:37 UTC, alanshaw commented
Ah ok, because you have to know in advance that `DATA` doesn't begin with a valid multistream message like `/bitswap/2.0.0`. In the case where the receiver responds `na`, `DATA` could be misconstrued as a continuation of the multistream negotiation.

2022-08-12 13:59 UTC, alanshaw commented
> The remaining theoretical pitfall whereby application data gets misinterpreted as another protocol proposal by a listener remains, however unlikely.
> https://github.com/libp2p/rust-libp2p/pull/1855

2022-08-30 10:53 UTC, achingbrain requested changes

2022-10-12 15:59 UTC, merged